import tkinter as tk
from tkinter import ttk
from tkinter import filedialog


class ProjectCreatorView(tk.Toplevel):
    def __init__(self, parent):
        tk.Toplevel.__init__(self, parent)
        self.title("Создание проекта")
        self.geometry("416x450+539+241")
        self.protocol('WM_DELETE_WINDOW', self.master.destroy)

        self.combobox = tk.StringVar()
        self.che60 = tk.IntVar()

        self.Label2 = tk.Label(self)
        self.Label2.place(relx=0.024, rely=0.134, height=21, width=104)
        self.Label2.configure(activebackground="#d9d9d9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(anchor='w')
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(compound='left')
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font="-family {Segoe UI} -size 9")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="#000000")
        self.Label2.configure(text='''Путь к каталогу:''')

        self.Label4 = tk.Label(self)
        self.Label4.place(relx=0.024, rely=0.333, height=21, width=94)
        self.Label4.configure(activebackground="#d9d9d9")
        self.Label4.configure(activeforeground="black")
        self.Label4.configure(anchor='w')
        self.Label4.configure(background="#d9d9d9")
        self.Label4.configure(compound='left')
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(font="-family {Segoe UI} -size 9")
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(highlightbackground="#d9d9d9")
        self.Label4.configure(highlightcolor="#000000")
        self.Label4.configure(text='''Язык проекта:''')

        self.Label5 = tk.Label(self)
        self.Label5.place(relx=0.024, rely=0.443, height=22, width=74)
        self.Label5.configure(activebackground="#d9d9d9")
        self.Label5.configure(activeforeground="black")
        self.Label5.configure(anchor='w')
        self.Label5.configure(background="#d9d9d9")
        self.Label5.configure(compound='left')
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(font="-family {Segoe UI} -size 9")
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(highlightbackground="#d9d9d9")
        self.Label5.configure(highlightcolor="#000000")
        self.Label5.configure(text='''Описание:''')

        self.Label6 = tk.Label(self)
        self.Label6.place(relx=0.024, rely=0.732, height=22, width=111)
        self.Label6.configure(activebackground="#d9d9d9")
        self.Label6.configure(activeforeground="black")
        self.Label6.configure(anchor='w')
        self.Label6.configure(background="#d9d9d9")
        self.Label6.configure(compound='left')
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(font="-family {Segoe UI} -size 9")
        self.Label6.configure(foreground="#000000")
        self.Label6.configure(highlightbackground="#d9d9d9")
        self.Label6.configure(highlightcolor="#000000")
        self.Label6.configure(text='''Защита паролем:''')

        self.Label7 = tk.Label(self)
        self.Label7.place(relx=0.024, rely=0.822, height=21, width=64)
        self.Label7.configure(activebackground="#d9d9d9")
        self.Label7.configure(activeforeground="black")
        self.Label7.configure(anchor='w')
        self.Label7.configure(background="#d9d9d9")
        self.Label7.configure(compound='left')
        self.Label7.configure(disabledforeground="#a3a3a3")
        self.Label7.configure(font="-family {Segoe UI} -size 9")
        self.Label7.configure(foreground="#000000")
        self.Label7.configure(highlightbackground="#d9d9d9")
        self.Label7.configure(highlightcolor="#000000")
        self.Label7.configure(text='''Пароль:''')

        self.Label1 = tk.Label(self)
        self.Label1.place(relx=0.024, rely=0.044, height=21, width=114)
        self.Label1.configure(activebackground="#d9d9d9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(anchor='w')
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(compound='left')
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Segoe UI} -size 9")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="#000000")
        self.Label1.configure(text='''Название проекта:''')

        self.cancel_button = tk.Button(self)
        self.cancel_button.place(relx=0.048, rely=0.899, height=36, width=157)
        self.cancel_button.configure(activebackground="#d9d9d9")
        self.cancel_button.configure(activeforeground="black")
        self.cancel_button.configure(background="#d9d9d9")
        self.cancel_button.configure(disabledforeground="#a3a3a3")
        self.cancel_button.configure(font="-family {Segoe UI} -size 9")
        self.cancel_button.configure(foreground="#000000")
        self.cancel_button.configure(highlightbackground="#d9d9d9")
        self.cancel_button.configure(highlightcolor="#000000")
        self.cancel_button.configure(text='''Отмена''', command=self.close)

        self.create_button = tk.Button(self)
        self.create_button.place(relx=0.577, rely=0.899, height=36, width=157)
        self.create_button.configure(activebackground="#d9d9d9")
        self.create_button.configure(activeforeground="black")
        self.create_button.configure(background="#d9d9d9")
        self.create_button.configure(disabledforeground="#a3a3a3")
        self.create_button.configure(font="-family {Segoe UI} -size 9")
        self.create_button.configure(foreground="#000000")
        self.create_button.configure(highlightbackground="#d9d9d9")
        self.create_button.configure(highlightcolor="#000000")
        self.create_button.configure(text='''Создать''')

        self.name_entry = tk.Entry(self)
        self.name_entry.place(relx=0.313, rely=0.044, height=20, relwidth=0.635)
        self.name_entry.configure(background="white")
        self.name_entry.configure(disabledforeground="#a3a3a3")
        self.name_entry.configure(font="-family {Courier New} -size 10")
        self.name_entry.configure(foreground="#000000")
        self.name_entry.configure(highlightbackground="#d9d9d9")
        self.name_entry.configure(highlightcolor="#000000")
        self.name_entry.configure(insertbackground="#000000")
        self.name_entry.configure(selectbackground="#d9d9d9")
        self.name_entry.configure(selectforeground="black")

        self.catalog_path = tk.Label(self)
        self.catalog_path.place(relx=0.313, rely=0.134, height=21, width=264)
        self.catalog_path.configure(activebackground="#d9d9d9")
        self.catalog_path.configure(activeforeground="black")
        self.catalog_path.configure(anchor='w')
        self.catalog_path.configure(background="#d9d9d9")
        self.catalog_path.configure(compound='left')
        self.catalog_path.configure(disabledforeground="#a3a3a3")
        self.catalog_path.configure(font="-family {Segoe UI} -size 9")
        self.catalog_path.configure(foreground="#000000")
        self.catalog_path.configure(highlightbackground="#d9d9d9")
        self.catalog_path.configure(highlightcolor="#000000")
        self.catalog_path.configure(text='''...''')

        self.choose_catalog_button = tk.Button(self)
        self.choose_catalog_button.place(relx=0.168, rely=0.2, height=26, width=287)
        self.choose_catalog_button.configure(activebackground="#d9d9d9")
        self.choose_catalog_button.configure(activeforeground="black")
        self.choose_catalog_button.configure(background="#d9d9d9")
        self.choose_catalog_button.configure(disabledforeground="#a3a3a3")
        self.choose_catalog_button.configure(font="-family {Segoe UI} -size 9")
        self.choose_catalog_button.configure(foreground="#000000")
        self.choose_catalog_button.configure(highlightbackground="#d9d9d9")
        self.choose_catalog_button.configure(highlightcolor="#000000")
        self.choose_catalog_button.configure(text='''Указать каталог...''')
        self.choose_catalog_button.configure(command=self.get_directory_path)

        self.lang_combobox = ttk.Combobox(self)
        self.lang_combobox.place(relx=0.313, rely=0.333, relheight=0.042, relwidth=0.642)
        self.lang_combobox.configure(font="-family {Segoe UI} -size 9")
        self.lang_combobox.configure(textvariable=self.combobox)

        self.description_text = tk.Text(self)
        self.description_text.place(relx=0.313, rely=0.439, relheight=0.25, relwidth=0.635)
        self.description_text.configure(background="white")
        self.description_text.configure(font="TkTextFont")
        self.description_text.configure(foreground="black")
        self.description_text.configure(highlightbackground="#d9d9d9")
        self.description_text.configure(highlightcolor="#000000")
        self.description_text.configure(insertbackground="#000000")
        self.description_text.configure(selectbackground="#d9d9d9")
        self.description_text.configure(selectforeground="black")
        self.description_text.configure(wrap="word")

        self.password_checkbox = tk.Checkbutton(self)
        self.password_checkbox.place(relx=0.313, rely=0.732, relheight=0.057, relwidth=0.05)
        self.password_checkbox.configure(activebackground="#d9d9d9")
        self.password_checkbox.configure(activeforeground="black")
        self.password_checkbox.configure(anchor='w')
        self.password_checkbox.configure(background="#d9d9d9")
        self.password_checkbox.configure(compound='left')
        self.password_checkbox.configure(disabledforeground="#a3a3a3")
        self.password_checkbox.configure(font="-family {Segoe UI} -size 9")
        self.password_checkbox.configure(foreground="#000000")
        self.password_checkbox.configure(highlightbackground="#d9d9d9")
        self.password_checkbox.configure(highlightcolor="#000000")
        self.password_checkbox.configure(justify='left')
        self.password_checkbox.configure(variable=self.che60)

        self.password_entry = tk.Entry(self)
        self.password_entry.place(relx=0.192, rely=0.822, height=20, relwidth=0.418)
        self.password_entry.configure(background="white")
        self.password_entry.configure(disabledforeground="#a3a3a3")
        self.password_entry.configure(font="-family {Courier New} -size 10")
        self.password_entry.configure(foreground="#000000")
        self.password_entry.configure(highlightbackground="#d9d9d9")
        self.password_entry.configure(highlightcolor="#000000")
        self.password_entry.configure(insertbackground="#000000")
        self.password_entry.configure(selectbackground="#d9d9d9")
        self.password_entry.configure(selectforeground="black")

    def close(self):
        self.destroy()

    def get_directory_path(self):
        directory_path = filedialog.askdirectory()
        if directory_path != "":
            self.catalog_path.config(text=directory_path)

    # Get window elements
    def get_fields(self):
        fields = {
            "name_text": self.name_entry,
            "path_text": self.catalog_path,
            "lang_combobox": self.lang_combobox,
            "description_text": self.description_text,
            "password_text": self.password_entry
        }

        return fields
